default_platform(:android)

platform :android do
  desc "Build a release APK"
  lane :build do
    gradle(
      project_dir: "./android",
      task: "clean assembleRelease",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
  end

  desc "Deploy release APK to Google Play Store internal track"
  lane :deploy_internal do
    build
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      aab: "./android/app/build/outputs/bundle/release/app-release.aab",
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.littlebuddha.app",
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy release APK to Google Play Store beta track"
  lane :deploy_beta do
    build
    upload_to_play_store(
      track: "beta",
      release_status: "draft",
      aab: "./android/app/build/outputs/bundle/release/app-release.aab",
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.littlebuddha.app",
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy release to Google Play Store production track"
  lane :deploy_production do
    build
    upload_to_play_store(
      track: "production",
      release_status: "draft",
      aab: "./android/app/build/outputs/bundle/release/app-release.aab",
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.littlebuddha.app",
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ios/LittleBuddha.xcodeproj")
    build_app(workspace: "ios/LittleBuddha.xcworkspace", scheme: "LittleBuddha")
    upload_to_testflight
  end
end
